### ISSUE TITLE
Panic

### ISSUE THREAD

**Issue by povilasv** [uw-labs/substrate#122]
```
panic: runtime error: hash of unhashable type gateway.SimpleMessage                                                                     

goroutine 28 [running]:                                             
github.com/uw-labs/substrate/internal/helper.(*AckOrderingSink).PublishMessages.func3(0x0, 0x0)                                         
        /go/src/github.com/uw-labs/substrate/internal/helper/sink_ack_ordering.go:63 +0x6a1                                             
golang.org/x/sync/errgroup.(*Group).Go.func1(0xc00019e570, 0xc00019e960)                                                                
        /go/src/golang.org/x/sync/errgroup/errgroup.go:57 +0x59                                                                         
created by golang.org/x/sync/errgroup.(*Group).Go                                                                                       
        /go/src/golang.org/x/sync/errgroup/errgroup.go:54 +0x66   
```

**Comment by mjgarton** [comment]
Thanks for opening this @povilasv 

This is different but partially related to #103 

As a workaround while we work this out, you can probably do something similar, i.e., use a pointer to `gateway.SimpleMessage` as the type.
